require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdbDeviceTestsController do

  # This should return the minimal set of attributes required to create a valid
  # AdbDeviceTest. As you add validations to AdbDeviceTest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdbDeviceTestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all adb_device_tests as @adb_device_tests" do
      adb_device_test = AdbDeviceTest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:adb_device_tests).should eq([adb_device_test])
    end
  end

  describe "GET show" do
    it "assigns the requested adb_device_test as @adb_device_test" do
      adb_device_test = AdbDeviceTest.create! valid_attributes
      get :show, {:id => adb_device_test.to_param}, valid_session
      assigns(:adb_device_test).should eq(adb_device_test)
    end
  end

  describe "GET new" do
    it "assigns a new adb_device_test as @adb_device_test" do
      get :new, {}, valid_session
      assigns(:adb_device_test).should be_a_new(AdbDeviceTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested adb_device_test as @adb_device_test" do
      adb_device_test = AdbDeviceTest.create! valid_attributes
      get :edit, {:id => adb_device_test.to_param}, valid_session
      assigns(:adb_device_test).should eq(adb_device_test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdbDeviceTest" do
        expect {
          post :create, {:adb_device_test => valid_attributes}, valid_session
        }.to change(AdbDeviceTest, :count).by(1)
      end

      it "assigns a newly created adb_device_test as @adb_device_test" do
        post :create, {:adb_device_test => valid_attributes}, valid_session
        assigns(:adb_device_test).should be_a(AdbDeviceTest)
        assigns(:adb_device_test).should be_persisted
      end

      it "redirects to the created adb_device_test" do
        post :create, {:adb_device_test => valid_attributes}, valid_session
        response.should redirect_to(AdbDeviceTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved adb_device_test as @adb_device_test" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdbDeviceTest.any_instance.stub(:save).and_return(false)
        post :create, {:adb_device_test => { "name" => "invalid value" }}, valid_session
        assigns(:adb_device_test).should be_a_new(AdbDeviceTest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdbDeviceTest.any_instance.stub(:save).and_return(false)
        post :create, {:adb_device_test => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested adb_device_test" do
        adb_device_test = AdbDeviceTest.create! valid_attributes
        # Assuming there are no other adb_device_tests in the database, this
        # specifies that the AdbDeviceTest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AdbDeviceTest.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => adb_device_test.to_param, :adb_device_test => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested adb_device_test as @adb_device_test" do
        adb_device_test = AdbDeviceTest.create! valid_attributes
        put :update, {:id => adb_device_test.to_param, :adb_device_test => valid_attributes}, valid_session
        assigns(:adb_device_test).should eq(adb_device_test)
      end

      it "redirects to the adb_device_test" do
        adb_device_test = AdbDeviceTest.create! valid_attributes
        put :update, {:id => adb_device_test.to_param, :adb_device_test => valid_attributes}, valid_session
        response.should redirect_to(adb_device_test)
      end
    end

    describe "with invalid params" do
      it "assigns the adb_device_test as @adb_device_test" do
        adb_device_test = AdbDeviceTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdbDeviceTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => adb_device_test.to_param, :adb_device_test => { "name" => "invalid value" }}, valid_session
        assigns(:adb_device_test).should eq(adb_device_test)
      end

      it "re-renders the 'edit' template" do
        adb_device_test = AdbDeviceTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdbDeviceTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => adb_device_test.to_param, :adb_device_test => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested adb_device_test" do
      adb_device_test = AdbDeviceTest.create! valid_attributes
      expect {
        delete :destroy, {:id => adb_device_test.to_param}, valid_session
      }.to change(AdbDeviceTest, :count).by(-1)
    end

    it "redirects to the adb_device_tests list" do
      adb_device_test = AdbDeviceTest.create! valid_attributes
      delete :destroy, {:id => adb_device_test.to_param}, valid_session
      response.should redirect_to(adb_device_tests_url)
    end
  end

end
